# Generated by Django 3.0.14 on 2022-04-07 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_allow_blank_wifi_host_ip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beerlogpoint',
            options={'managed': True, 'ordering': ['log_time'], 'verbose_name': 'Beer Log Point', 'verbose_name_plural': 'Beer Log Points'},
        ),
        migrations.AlterModelOptions(
            name='pindevice',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='sensordevice',
            options={'managed': True, 'verbose_name': 'Sensor Device', 'verbose_name_plural': 'Sensor Devices'},
        ),
    ]
