# Generated by Django 3.0.14 on 2022-04-07 14:33

import backups.models
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('filename_prefix', models.CharField(default=backups.models.default_filename_prefix, help_text="The filename prefix for this backup's archive", max_length=128)),
            ],
            options={
                'permissions': [('restore_backup', 'Can restore from a backup (which can overwrite all data in Fermentrack)')],
            },
        ),
    ]
